#!/bin/bash

METADATA_LOCAL_IPV4=`curl http://169.254.169.254/2014-02-25/meta-data/local-ipv4`

consul-template \
  -consul $METADATA_LOCAL_IPV4:8500 \
  -template "/tmp/index.html.ctmpl:/var/www/html/index.html" \
  -retry 5s \
  -once
